# Generated by Django 2.1.2 on 2018-12-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0002_friend_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='likes',
        ),
        migrations.AddField(
            model_name='friend',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
