# Generated by Django 2.1.2 on 2018-12-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0004_friend_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='gender',
            field=models.TextField(choices=[(1, 'Male'), (2, 'Female')]),
        ),
    ]
