# Generated by Django 2.1.2 on 2018-12-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0008_auto_20181229_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='line',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friend',
            name='birthplace',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
